name: ammu_app
description: "A new Flutter project."
# publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Valid dependencies only
  flutter_blue_plus: any
  syncfusion_flutter_gauges: any
  google_maps_flutter: any
  cupertino_icons: ^1.0.8
  device_preview: any
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.9+2
  http: ^1.2.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  fl_chart: ^0.68.0
  intl: ^0.20.2
  google_sign_in: ^6.1.5
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.6
  flutter_svg: ^2.0.7
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Use latest

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/108.png
    - assets/add.png
    - assets/applepay.png
    - assets/assignments.png
    - assets/background.png
    - assets/computer.png
    - assets/events.png
    - assets/facebook.png
    - assets/family.png
    - assets/girl.png
    - assets/google.png
    - assets/home.png
    - assets/home2.png
    - assets/illustrator.png
    - assets/khathija.png
    - assets/library.png
    - assets/library2.png
    - assets/loginpage.png
    - assets/map.png
    - assets/marks.png
    - assets/ngo.png
    - assets/others.png
    - assets/parents.png
    - assets/park.png
    - assets/paytm.png
    - assets/police.png
    - assets/rose.png
    - assets/staff.png
    - assets/staff2.png
    - assets/stripe.png
    - assets/sub.png
    - assets/teacher.png
    - assets/upi.png
    - assets/VMschool.png
    # - assets/incident1.png
    # - assets/incident2.png
    # - assets/parent_alert.png
    # - assets/staff_alert.png
    # - assets/performance.png
    # - assets/smartwatch_icon.png
    # - assets/contact_icon.png
    - assets/staff0.jpg
    - assets/parents1.jpg


