name: ammu_app
description: "A new Flutter project."
# publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Valid dependencies only
  flutter_blue_plus: any
  syncfusion_flutter_gauges: any
  google_maps_flutter: any
  cupertino_icons: ^1.0.8
  device_preview: any
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.9+2
  http: ^1.2.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  fl_chart: ^0.68.0
  intl: ^0.20.2
  google_sign_in: ^6.1.5
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.6
  flutter_svg: ^2.0.7
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/girl.png
    - assets/loginpage.png
    - assets/illustrator.png
    - assets/google.png
    - assets/facebook.png
    - assets/background.png
    - assets/police.png
    - assets/family.png
    - assets/108.png
    - assets/staff.png
    - assets/ngo.png
